### ISSUE TITLE
compute_targets_of_locations问题

### ISSUE THREAD

**Issue by Cydia2018** [feifeiwei/FCOS.pytorch#1]
错误：
 File "/home/benkebishe01/FCOS.pytorch/models/loss_modules.py", line 215, in compute_targets_of_locations
    is_in_boxes = reg_targets_per_img.min(dim=2)[0] > 0   
RuntimeError: cannot perform reduction function min on tensor with no elements because the operation does not have an identity

亲，这个错误运行几轮batch后就出现，不固定。是我的数据集有问题吗，谢谢！

**Comment by feifeiwei** [comment]
@Cydia2018  改了一下  你再试试

**Comment by Cydia2018** [comment]
> @Cydia2018 改了一下 你再试试

您好，感谢你的解答。修改之后训练可以进行，但是box_loss一直为-30左右，我在VOC数据集上训练70epoch后，找了一些图片用demo测试，还是找不到物体（我把阈值调到很低）。期待您的回复！

**Comment by feifeiwei** [comment]
@Cydia2018  label格式调整对了吗
